events {
}

http {

    upstream flask_servers {
        server web:5000;
        # Add additional Flask instances here if needed
    }

    server {
        listen 5000;

        location / {
            proxy_pass http://flask_servers;
        }
    }
}