services:
  web:
    environment:
      - REDIS_HOST=myRedisCache
      - REDIS_PORT=6379
      - FLASK_PASS=${FLASK_PASS}
    build: .
    expose:
      - "5000"
    depends_on:
      - myRedisCache
  loadbalancer:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    depends_on:
      - web
  myRedisCache:
    image: redis:latest 
    volumes:
      - redis-data:/data
    
  
volumes:
  redis-data: