services:
  web:
    environment:
      - REDIS_HOST=myRedisCache
      - REDIS_PORT=6379
      - FLASK_PASS=${FLASK_PASS}
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - myRedisCache

  myRedisCache:
    image: redis:latest 
    volumes:
      - redis-data:/data
    
  
volumes:
  redis-data: